type Query {
  # searchUsers(username: String!, paginationValue: String): [User!]
  # searchRepositories(repositoryName: String!, paginationValue: String): [Repository!]
  # getDirectoryContents(repositoryName: String!, directory: String!): [File!]
  
  # downloadFile(repositoryName: String!, filePath: String!): Upload
  # downloadDirectory(repositoryName: String!, directory: String!): Upload
}

# type Mutation {
#   # uploadFile(repositoryName: String!, file: Upload!, filePath: String!)
# }

type User {
  id: String!
  name: String!
  ownedRepositories: [Repository!]
  sharedRepositories: [Repository!]
}

type Repository {
  id: String!
  name: String!
  ownerUsers: [User!]!
  sharedUsers: [User!]
}

type File {
  id: String!
  name: String!
  size: String!
  path: String!
}

type Directory {
  id: String!
  name: String!
  size: String
}